PREFIX dblp: <https://dblp.org/rdf/schema#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

CONSTRUCT {
  ?pub dblp:title ?title ;
       dblp:yearOfPublication ?year ;
       dblp:createdBy ?author ;
       dblp:publishedInStream ?stream ;
       rdf:type ?pubclass .

  ?author dblp:primaryCreatorName ?name ;
          rdf:type dblp:Creator .

  ?stream dblp:streamTitle ?streamTitle ;
          rdf:type ?streamclass .
}
WHERE {

  VALUES ?stream {
    <https://dblp.org/streams/journals/ftir>
    <https://dblp.org/streams/journals/ijirr>
    <https://dblp.org/streams/journals/ijmir>
    <https://dblp.org/streams/journals/ipm>
    <https://dblp.org/streams/journals/ir>
    <https://dblp.org/streams/journals/jasis>
    <https://dblp.org/streams/journals/sigir>
    <https://dblp.org/streams/journals/tismir>
    <https://dblp.org/streams/journals/tist>
    <https://dblp.org/streams/journals/tois>
    <https://dblp.org/streams/journals/tweb>
    <https://dblp.org/streams/journals/wwwj>
    <https://dblp.org/streams/conf/adcs>
    <https://dblp.org/streams/conf/airs>
    <https://dblp.org/streams/conf/ccir>
    <https://dblp.org/streams/conf/ceri>
    <https://dblp.org/streams/conf/chiir>
    <https://dblp.org/streams/conf/cikm>
    <https://dblp.org/streams/conf/civr>
    <https://dblp.org/streams/conf/clef>
    <https://dblp.org/streams/conf/coria>
    <https://dblp.org/streams/conf/desires>
    <https://dblp.org/streams/conf/dir>
    <https://dblp.org/streams/conf/ecir>
    <https://dblp.org/streams/conf/fdia>
    <https://dblp.org/streams/conf/fire>
    <https://dblp.org/streams/conf/ictir>
    <https://dblp.org/streams/conf/irfc>
    <https://dblp.org/streams/conf/ismir>
    <https://dblp.org/streams/conf/mir>
    <https://dblp.org/streams/conf/ntcir>
    <https://dblp.org/streams/conf/sigir>
    <https://dblp.org/streams/conf/spire>
    <https://dblp.org/streams/conf/trec>
    <https://dblp.org/streams/conf/wsdm>
    <https://dblp.org/streams/conf/www>
  }

  ?pub dblp:publishedInStream ?stream ;
       dblp:title ?title ;
       dblp:createdBy ?author .

  OPTIONAL { ?pub dblp:yearOfPublication ?year . }
  OPTIONAL { ?pub rdf:type ?pubclass . 
    FILTER(?pubclass != dblp:Publication)
  }

  OPTIONAL { ?author dblp:primaryCreatorName ?name . }

  OPTIONAL { ?stream dblp:streamTitle ?streamTitle . }
  OPTIONAL {
      ?stream rdf:type ?streamclass .
      FILTER(?streamclass != dblp:Stream)
  }
}
LIMIT __LIMIT__
OFFSET __OFFSET__